# Generated by Django 4.1 on 2023-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_car',
            field=models.CharField(default='Model Y', max_length=200, verbose_name='Модель авто'),
            preserve_default=False,
        ),
    ]
