# Generated by Django 4.1 on 2023-07-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_comment_comment_shop_commen_model_3ef185_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=600, verbose_name='Відгук'),
        ),
    ]
