# Generated by Django 4.1 on 2023-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_page',
            field=models.BooleanField(default=False, verbose_name='Товар на головній сторінці'),
        ),
    ]
