# Generated by Django 4.1 on 2023-07-16 15:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_mainpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='media',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/mainpage', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Відео'),
        ),
    ]
