# Generated by Django 4.1 on 2023-07-16 15:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_mainpage_media_mainpage_image_mainpage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Актуальне'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mainpage', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Відео'),
        ),
    ]
