# Generated by Django 4.1 on 2023-07-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_mainpage_available_alter_mainpage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Головне медіа', 'verbose_name_plural': 'Головні медіа'},
        ),
    ]
