# Generated by Django 4.1 on 2023-07-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_category_created_by_category_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамілія')),
                ('mobile_phone', models.CharField(max_length=15, verbose_name='Мобільний телефон')),
                ('done', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Записка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Час обновлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновив(ла)')),
            ],
            options={
                'verbose_name': 'Головне медіа',
                'verbose_name_plural': 'Головні медіа',
            },
        ),
    ]
